#\!/bin/bash
echo "Browse mode:"
echo "    nf-fa-globe"
echo "  󰖟  nf-md-web"
echo "    nf-oct-globe"
echo ""
echo "Control mode:"
echo "    nf-fa-gamepad"
echo "    nf-cod-terminal"
echo "    nf-fa-keyboard_o"
echo "  󰊖  nf-md-gamepad"
echo "    nf-fa-cog"
echo "    nf-fa-sliders"
